name: Build and publish packages

on:
  push:
    branches:
      - main

env:
  IMAGE: ${{ github.repository }} # lorisleiva/laravel-docker

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - tag: 'latest'
            php: '8.2'
          - tag: 'stable'
            php: '8.2'
          - tag: '8.2'
            php: '8.2'
          - tag: '8.1'
            php: '8.1'
          - tag: '8.0'
            php: '8.0'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ${{ matrix.php }}
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ env.IMAGE }}:${{ matrix.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
